export const CovenantFactoryABI = [
  { type: 'event', name: 'CovenantCreated', inputs: [{ name: 'proxy', type: 'address', indexed: true }, { name: 'implementation', type: 'address', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'salt', type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'ImplementationUpdated', inputs: [{ name: 'oldImplementation', type: 'address', indexed: true }, { name: 'newImplementation', type: 'address', indexed: true }] },
  { type: 'event', name: 'RegistryUpdated', inputs: [{ name: 'oldRegistry', type: 'address', indexed: true }, { name: 'newRegistry', type: 'address', indexed: true }] },
  { type: 'error', name: 'InvalidImplementation' },
  { type: 'error', name: 'InvalidRegistry' },
  { type: 'error', name: 'InvalidInitializer' },
  { type: 'error', name: 'CovenantCreationFailed' },
  { type: 'function', name: 'createCovenant', stateMutability: 'nonpayable', inputs: [{ name: 'salt', type: 'bytes32' }, { name: 'initData', type: 'bytes' }], outputs: [{ name: 'proxy', type: 'address' }] },
  { type: 'function', name: 'predictCovenantAddress', stateMutability: 'view', inputs: [{ name: 'salt', type: 'bytes32' }, { name: 'initData', type: 'bytes' }], outputs: [{ name: 'predicted', type: 'address' }] },
  { type: 'function', name: 'implementation', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'registry', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'setImplementation', stateMutability: 'nonpayable', inputs: [{ name: 'newImplementation', type: 'address' }], outputs: [] },
  { type: 'function', name: 'setRegistry', stateMutability: 'nonpayable', inputs: [{ name: 'newRegistry', type: 'address' }], outputs: [] },
] as const;

export const CovenantRegistryABI = [
  { type: 'event', name: 'CovenantRegistered', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'proxy', type: 'address', indexed: true }, { name: 'creator', type: 'address', indexed: true }] },
  { type: 'event', name: 'CovenantDeregistered', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'proxy', type: 'address', indexed: true }] },
  { type: 'error', name: 'OnlyFactory' },
  { type: 'error', name: 'AlreadyRegistered' },
  { type: 'error', name: 'CovenantNotFound' },
  { type: 'error', name: 'InvalidCovenantId' },
  { type: 'function', name: 'register', stateMutability: 'nonpayable', inputs: [{ name: 'proxy', type: 'address' }, { name: 'creator', type: 'address' }], outputs: [{ name: 'covenantId', type: 'uint256' }] },
  { type: 'function', name: 'deregister', stateMutability: 'nonpayable', inputs: [{ name: 'covenantId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getCovenant', stateMutability: 'view', inputs: [{ name: 'covenantId', type: 'uint256' }], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'getCovenantId', stateMutability: 'view', inputs: [{ name: 'proxy', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getCovenantsByCreator', stateMutability: 'view', inputs: [{ name: 'creator', type: 'address' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'totalCovenants', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'factory', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
] as const;

export const CovenantImplementationABI = [
  { type: 'event', name: 'CovenantInitialized', inputs: [{ name: 'factory', type: 'address', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'covenantId', type: 'uint256', indexed: true }] },
  { type: 'event', name: 'CovenantStateChanged', inputs: [{ name: 'oldState', type: 'uint8', indexed: true }, { name: 'newState', type: 'uint8', indexed: true }] },
  { type: 'error', name: 'AlreadyInitialized' },
  { type: 'error', name: 'Unauthorized' },
  { type: 'error', name: 'InvalidStateTransition' },
  { type: 'function', name: 'initialize', stateMutability: 'nonpayable', inputs: [{ name: 'creator', type: 'address' }, { name: 'covenantId', type: 'uint256' }, { name: 'params', type: 'bytes' }], outputs: [] },
  { type: 'function', name: 'activate', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'pause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'resolve', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'terminate', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'state', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
  { type: 'function', name: 'creator', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'covenantId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantProxyABI = [
  { type: 'error', name: 'UnauthorizedUpgrade' },
  { type: 'error', name: 'InvalidImplementation' },
  { type: 'function', name: 'upgradeToAndCall', stateMutability: 'nonpayable', inputs: [{ name: 'newImplementation', type: 'address' }, { name: 'data', type: 'bytes' }], outputs: [] },
  { type: 'function', name: 'implementation', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'admin', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'changeAdmin', stateMutability: 'nonpayable', inputs: [{ name: 'newAdmin', type: 'address' }], outputs: [] },
] as const;

export const CovenantEventsABI = [
  { type: 'event', name: 'CovenantCreated', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'proxy', type: 'address', indexed: true }] },
  { type: 'event', name: 'CovenantUpdated', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'updateType', type: 'bytes32', indexed: true }, { name: 'data', type: 'bytes', indexed: false }] },
  { type: 'event', name: 'CovenantActivated', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'timestamp', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'CovenantPaused', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'timestamp', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'CovenantResolved', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'timestamp', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'CovenantTerminated', inputs: [{ name: 'covenantId', type: 'uint256', indexed: true }, { name: 'timestamp', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TaskCreated', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'covenantId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskAssigned', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'assignee', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskSubmitted', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'proofHash', type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'TaskApproved', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'approver', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskRejected', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'approver', type: 'address', indexed: true }, { name: 'reason', type: 'string', indexed: false }] },
  { type: 'event', name: 'ReputationStaked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ReputationUnstaked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ReputationUpdated', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'newScore', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ReputationDecayed', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'decayAmount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'DisputeOpened', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'taskId', type: 'uint256', indexed: true }, { name: 'initiator', type: 'address', indexed: true }] },
  { type: 'event', name: 'DisputeEvidenceSubmitted', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'submitter', type: 'address', indexed: true }, { name: 'evidenceHash', type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'DisputeVoteCast', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'voter', type: 'address', indexed: true }, { name: 'vote', type: 'uint8', indexed: false }] },
  { type: 'event', name: 'DisputeResolved', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'outcome', type: 'uint8', indexed: false }] },
  { type: 'event', name: 'DisputeAppealed', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'appellant', type: 'address', indexed: true }] },
  { type: 'event', name: 'ProposalCreated', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: 'proposer', type: 'address', indexed: true }, { name: 'description', type: 'string', indexed: false }] },
  { type: 'event', name: 'VoteCast', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: 'voter', type: 'address', indexed: true }, { name: 'support', type: 'uint8', indexed: false }, { name: 'votes', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ProposalExecuted', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'ProposalCanceled', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'MessageSent', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'targetChain', type: 'uint16', indexed: true }, { name: 'targetContract', type: 'address', indexed: false }] },
  { type: 'event', name: 'MessageReceived', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'sourceChain', type: 'uint16', indexed: true }, { name: 'sourceContract', type: 'address', indexed: false }] },
  { type: 'event', name: 'EmergencyPaused', inputs: [{ name: 'pauser', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'EmergencyUnpaused', inputs: [{ name: 'unpauser', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'UpgradeAuthorized', inputs: [{ name: 'implementation', type: 'address', indexed: true }, { name: 'effectiveTime', type: 'uint256', indexed: false }] },
] as const;

export const TaskMarketABI = [
  { type: 'event', name: 'TaskCreated', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'covenantId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'reward', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TaskAssigned', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'assignee', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskSubmitted', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'proofHash', type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'TaskCompleted', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'assignee', type: 'address', indexed: true }, { name: 'reward', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TaskDisputed', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: 'disputeId', type: 'uint256', indexed: true }] },
  { type: 'event', name: 'TaskCancelled', inputs: [{ name: 'taskId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'InvalidCovenant' },
  { type: 'error', name: 'InvalidReward' },
  { type: 'error', name: 'InvalidDeadline' },
  { type: 'error', name: 'TaskNotOpen' },
  { type: 'error', name: 'TaskNotAssigned' },
  { type: 'error', name: 'TaskNotSubmitted' },
  { type: 'error', name: 'UnauthorizedTaskAction' },
  { type: 'error', name: 'DeadlinePassed' },
  { type: 'function', name: 'createTask', stateMutability: 'payable', inputs: [{ name: 'covenantId', type: 'uint256' }, { name: 'reward', type: 'uint256' }, { name: 'rewardToken', type: 'address' }, { name: 'deadline', type: 'uint256' }, { name: 'metadataHash', type: 'bytes32' }], outputs: [{ name: 'taskId', type: 'uint256' }] },
  { type: 'function', name: 'assignTask', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'submitTask', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }, { name: 'proofHash', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'completeTask', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'disputeTask', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [{ name: 'disputeId', type: 'uint256' }] },
  { type: 'function', name: 'cancelTask', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getTask', stateMutability: 'view', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'id', type: 'uint256' }, { name: 'covenantId', type: 'uint256' }, { name: 'creator', type: 'address' }, { name: 'assignee', type: 'address' }, { name: 'reward', type: 'uint256' }, { name: 'rewardToken', type: 'address' }, { name: 'deadline', type: 'uint256' }, { name: 'status', type: 'uint8' }, { name: 'metadataHash', type: 'bytes32' }] }] },
  { type: 'function', name: 'getTasksByCovenant', stateMutability: 'view', inputs: [{ name: 'covenantId', type: 'uint256' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getTasksByAssignee', stateMutability: 'view', inputs: [{ name: 'assignee', type: 'address' }], outputs: [{ type: 'uint256[]' }] },
] as const;

export const TaskAuctionABI = [
  { type: 'event', name: 'AuctionCreated', inputs: [{ name: 'auctionId', type: 'uint256', indexed: true }, { name: 'taskId', type: 'uint256', indexed: true }, { name: 'startPrice', type: 'uint256', indexed: false }, { name: 'endPrice', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'BidPlaced', inputs: [{ name: 'auctionId', type: 'uint256', indexed: true }, { name: 'bidder', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'AuctionSettled', inputs: [{ name: 'auctionId', type: 'uint256', indexed: true }, { name: 'winner', type: 'address', indexed: true }, { name: 'winningBid', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'AuctionCancelled', inputs: [{ name: 'auctionId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'AuctionNotFound' },
  { type: 'error', name: 'AuctionNotActive' },
  { type: 'error', name: 'BidTooLow' },
  { type: 'error', name: 'AuctionNotEnded' },
  { type: 'error', name: 'AlreadySettled' },
  { type: 'error', name: 'UnauthorizedCancellation' },
  { type: 'function', name: 'createAuction', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }, { name: 'startPrice', type: 'uint256' }, { name: 'endPrice', type: 'uint256' }, { name: 'duration', type: 'uint256' }], outputs: [{ name: 'auctionId', type: 'uint256' }] },
  { type: 'function', name: 'placeBid', stateMutability: 'payable', inputs: [{ name: 'auctionId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'settleAuction', stateMutability: 'nonpayable', inputs: [{ name: 'auctionId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'cancelAuction', stateMutability: 'nonpayable', inputs: [{ name: 'auctionId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getCurrentPrice', stateMutability: 'view', inputs: [{ name: 'auctionId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getAuction', stateMutability: 'view', inputs: [{ name: 'auctionId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'taskId', type: 'uint256' }, { name: 'startPrice', type: 'uint256' }, { name: 'endPrice', type: 'uint256' }, { name: 'startTime', type: 'uint256' }, { name: 'duration', type: 'uint256' }, { name: 'highestBidder', type: 'address' }, { name: 'highestBid', type: 'uint256' }, { name: 'settled', type: 'bool' }] }] },
] as const;

export const TaskEscrowABI = [
  { type: 'event', name: 'EscrowCreated', inputs: [{ name: 'escrowId', type: 'uint256', indexed: true }, { name: 'taskId', type: 'uint256', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'EscrowFunded', inputs: [{ name: 'escrowId', type: 'uint256', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'EscrowReleased', inputs: [{ name: 'escrowId', type: 'uint256', indexed: true }, { name: 'payee', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'EscrowRefunded', inputs: [{ name: 'escrowId', type: 'uint256', indexed: true }, { name: 'payer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'EscrowDisputed', inputs: [{ name: 'escrowId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'EscrowNotFound' },
  { type: 'error', name: 'EscrowAlreadyFunded' },
  { type: 'error', name: 'EscrowAlreadyReleased' },
  { type: 'error', name: 'EscrowAlreadyRefunded' },
  { type: 'error', name: 'InsufficientFunds' },
  { type: 'error', name: 'UnauthorizedRelease' },
  { type: 'error', name: 'InvalidToken' },
  { type: 'function', name: 'createEscrow', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }, { name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'payee', type: 'address' }], outputs: [{ name: 'escrowId', type: 'uint256' }] },
  { type: 'function', name: 'fundEscrow', stateMutability: 'payable', inputs: [{ name: 'escrowId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'releaseEscrow', stateMutability: 'nonpayable', inputs: [{ name: 'escrowId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'refundEscrow', stateMutability: 'nonpayable', inputs: [{ name: 'escrowId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'disputeEscrow', stateMutability: 'nonpayable', inputs: [{ name: 'escrowId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getEscrow', stateMutability: 'view', inputs: [{ name: 'escrowId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'taskId', type: 'uint256' }, { name: 'amount', type: 'uint256' }, { name: 'token', type: 'address' }, { name: 'payer', type: 'address' }, { name: 'payee', type: 'address' }, { name: 'state', type: 'uint8' }] }] },
  { type: 'function', name: 'getEscrowByTask', stateMutability: 'view', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
] as const;

export const TaskReviewABI = [
  { type: 'event', name: 'ReviewSubmitted', inputs: [{ name: 'reviewId', type: 'uint256', indexed: true }, { name: 'taskId', type: 'uint256', indexed: true }, { name: 'reviewer', type: 'address', indexed: true }, { name: 'rating', type: 'uint8', indexed: false }] },
  { type: 'event', name: 'ReviewUpdated', inputs: [{ name: 'reviewId', type: 'uint256', indexed: true }, { name: 'newRating', type: 'uint8', indexed: false }] },
  { type: 'error', name: 'InvalidRating' },
  { type: 'error', name: 'ReviewAlreadyExists' },
  { type: 'error', name: 'TaskNotCompleted' },
  { type: 'error', name: 'UnauthorizedReviewer' },
  { type: 'function', name: 'submitReview', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }, { name: 'reviewee', type: 'address' }, { name: 'rating', type: 'uint8' }, { name: 'commentHash', type: 'bytes32' }], outputs: [{ name: 'reviewId', type: 'uint256' }] },
  { type: 'function', name: 'updateReview', stateMutability: 'nonpayable', inputs: [{ name: 'reviewId', type: 'uint256' }, { name: 'newRating', type: 'uint8' }, { name: 'newCommentHash', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'getReview', stateMutability: 'view', inputs: [{ name: 'reviewId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'reviewId', type: 'uint256' }, { name: 'taskId', type: 'uint256' }, { name: 'reviewer', type: 'address' }, { name: 'reviewee', type: 'address' }, { name: 'rating', type: 'uint8' }, { name: 'commentHash', type: 'bytes32' }, { name: 'createdAt', type: 'uint256' }] }] },
  { type: 'function', name: 'getReviewsByTask', stateMutability: 'view', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getReviewsByReviewee', stateMutability: 'view', inputs: [{ name: 'reviewee', type: 'address' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getAverageRating', stateMutability: 'view', inputs: [{ name: 'reviewee', type: 'address' }], outputs: [{ name: 'average', type: 'uint256' }, { name: 'count', type: 'uint256' }] },
] as const;

export const TaskDisputeABI = [
  { type: 'event', name: 'TaskDisputeInitiated', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'taskId', type: 'uint256', indexed: true }, { name: 'initiator', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskDisputeResponded', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'respondent', type: 'address', indexed: true }] },
  { type: 'event', name: 'TaskDisputeResolved', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'outcome', type: 'uint8', indexed: false }] },
  { type: 'error', name: 'TaskDisputeNotFound' },
  { type: 'error', name: 'TaskDisputeAlreadyResolved' },
  { type: 'error', name: 'UnauthorizedInitiator' },
  { type: 'error', name: 'InvalidTaskStatus' },
  { type: 'function', name: 'initiateDispute', stateMutability: 'nonpayable', inputs: [{ name: 'taskId', type: 'uint256' }, { name: 'reasonHash', type: 'bytes32' }], outputs: [{ name: 'disputeId', type: 'uint256' }] },
  { type: 'function', name: 'respondToDispute', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'resolveTaskDispute', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'outcome', type: 'uint8' }], outputs: [] },
  { type: 'function', name: 'getTaskDispute', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'disputeId', type: 'uint256' }, { name: 'taskId', type: 'uint256' }, { name: 'initiator', type: 'address' }, { name: 'respondent', type: 'address' }, { name: 'initiatedAt', type: 'uint256' }, { name: 'status', type: 'uint8' }, { name: 'outcome', type: 'uint8' }, { name: 'reasonHash', type: 'bytes32' }] }] },
  { type: 'function', name: 'getDisputesByTask', stateMutability: 'view', inputs: [{ name: 'taskId', type: 'uint256' }], outputs: [{ type: 'uint256[]' }] },
] as const;

export const DisputeDAOABI = [
  { type: 'event', name: 'ParamsUpdated', inputs: [{ name: 'paramName', type: 'bytes32', indexed: false }, { name: 'oldValue', type: 'uint256', indexed: false }, { name: 'newValue', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TreasuryWithdrawal', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'recipient', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'InvalidParam' },
  { type: 'error', name: 'UnauthorizedUpdate' },
  { type: 'function', name: 'updateParams', stateMutability: 'nonpayable', inputs: [{ name: 'params', type: 'tuple', components: [{ name: 'minStake', type: 'uint256' }, { name: 'votingPeriod', type: 'uint256' }, { name: 'quorum', type: 'uint256' }, { name: 'appealThreshold', type: 'uint256' }] }], outputs: [] },
  { type: 'function', name: 'getParams', stateMutability: 'view', inputs: [], outputs: [{ type: 'tuple', components: [{ name: 'minStake', type: 'uint256' }, { name: 'votingPeriod', type: 'uint256' }, { name: 'quorum', type: 'uint256' }, { name: 'appealThreshold', type: 'uint256' }] }] },
  { type: 'function', name: 'withdrawTreasury', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }, { name: 'recipient', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
] as const;

export const DisputeResolutionABI = [
  { type: 'event', name: 'DisputeResolved', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'outcome', type: 'uint8', indexed: false }, { name: 'detailsHash', type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'ResolutionExecuted', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'DisputeNotFound' },
  { type: 'error', name: 'DisputeAlreadyResolved' },
  { type: 'error', name: 'InvalidOutcome' },
  { type: 'error', name: 'ExecutionFailed' },
  { type: 'function', name: 'resolveDispute', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'outcome', type: 'uint8' }, { name: 'detailsHash', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'executeResolution', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getResolution', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ name: 'outcome', type: 'uint8' }, { name: 'detailsHash', type: 'bytes32' }, { name: 'executed', type: 'bool' }] },
  { type: 'function', name: 'canAppeal', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
] as const;

export const DisputeJuryABI = [
  { type: 'event', name: 'JurorRegistered', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'stake', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'JurorSelected', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'juror', type: 'address', indexed: true }] },
  { type: 'event', name: 'JurorSlashed', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'InsufficientJurorStake' },
  { type: 'error', name: 'JurorAlreadyRegistered' },
  { type: 'error', name: 'JurorNotFound' },
  { type: 'error', name: 'SelectionFailed' },
  { type: 'function', name: 'registerJuror', stateMutability: 'nonpayable', inputs: [{ name: 'stake', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'unregisterJuror', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'selectJury', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'jurySize', type: 'uint256' }], outputs: [{ type: 'address[]' }] },
  { type: 'function', name: 'slashJuror', stateMutability: 'nonpayable', inputs: [{ name: 'juror', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getJuror', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'account', type: 'address' }, { name: 'stake', type: 'uint256' }, { name: 'selectionScore', type: 'uint256' }, { name: 'active', type: 'bool' }] }] },
  { type: 'function', name: 'getJurorsForDispute', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'address[]' }] },
] as const;

export const DisputeVotingABI = [
  { type: 'event', name: 'VoteCast', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'voter', type: 'address', indexed: true }, { name: 'choice', type: 'uint8', indexed: false }, { name: 'weight', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'VotingClosed', inputs: [{ name: 'disputeId', type: 'uint256', indexed: true }, { name: 'outcome', type: 'uint8', indexed: false }] },
  { type: 'error', name: 'VotingNotOpen' },
  { type: 'error', name: 'VotingAlreadyClosed' },
  { type: 'error', name: 'VotingEnded' },
  { type: 'error', name: 'VotingNotEnded' },
  { type: 'error', name: 'AlreadyVoted' },
  { type: 'error', name: 'InvalidChoice' },
  { type: 'error', name: 'UnauthorizedVoter' },
  { type: 'function', name: 'castVote', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'choice', type: 'uint8' }], outputs: [] },
  { type: 'function', name: 'closeVoting', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ name: 'outcome', type: 'uint8' }] },
  { type: 'function', name: 'getVote', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'voter', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'voter', type: 'address' }, { name: 'choice', type: 'uint8' }, { name: 'weight', type: 'uint256' }, { name: 'timestamp', type: 'uint256' }] }] },
  { type: 'function', name: 'getVoteTally', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'uint256[3]' }] },
  { type: 'function', name: 'hasVoted', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'voter', type: 'address' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getVotingEndTime', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
] as const;

export const DisputeEvidenceABI = [
  { type: 'event', name: 'EvidenceSubmitted', inputs: [{ name: 'evidenceId', type: 'uint256', indexed: true }, { name: 'disputeId', type: 'uint256', indexed: true }, { name: 'submitter', type: 'address', indexed: true }, { name: 'evidenceHash', type: 'bytes32', indexed: false }] },
  { type: 'error', name: 'InvalidEvidence' },
  { type: 'error', name: 'EvidencePeriodClosed' },
  { type: 'error', name: 'UnauthorizedSubmitter' },
  { type: 'function', name: 'submitEvidence', stateMutability: 'nonpayable', inputs: [{ name: 'disputeId', type: 'uint256' }, { name: 'evidenceHash', type: 'bytes32' }, { name: 'metadataHash', type: 'bytes32' }], outputs: [{ name: 'evidenceId', type: 'uint256' }] },
  { type: 'function', name: 'getEvidence', stateMutability: 'view', inputs: [{ name: 'evidenceId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'evidenceId', type: 'uint256' }, { name: 'disputeId', type: 'uint256' }, { name: 'submitter', type: 'address' }, { name: 'evidenceHash', type: 'bytes32' }, { name: 'metadataHash', type: 'bytes32' }, { name: 'submittedAt', type: 'uint256' }] }] },
  { type: 'function', name: 'getEvidenceByDispute', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getEvidencePeriodEnd', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
] as const;

export const DisputeAppealABI = [
  { type: 'event', name: 'AppealFiled', inputs: [{ name: 'appealId', type: 'uint256', indexed: true }, { name: 'disputeId', type: 'uint256', indexed: true }, { name: 'appellant', type: 'address', indexed: true }, { name: 'bond', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'AppealResolved', inputs: [{ name: 'appealId', type: 'uint256', indexed: true }, { name: 'status', type: 'uint8', indexed: false }] },
  { type: 'error', name: 'AppealNotAllowed' },
  { type: 'error', name: 'AppealPeriodExpired' },
  { type: 'error', name: 'InsufficientAppealBond' },
  { type: 'error', name: 'AppealAlreadyResolved' },
  { type: 'function', name: 'fileAppeal', stateMutability: 'payable', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ name: 'appealId', type: 'uint256' }] },
  { type: 'function', name: 'resolveAppeal', stateMutability: 'nonpayable', inputs: [{ name: 'appealId', type: 'uint256' }, { name: 'status', type: 'uint8' }], outputs: [] },
  { type: 'function', name: 'getAppeal', stateMutability: 'view', inputs: [{ name: 'appealId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'appealId', type: 'uint256' }, { name: 'disputeId', type: 'uint256' }, { name: 'appellant', type: 'address' }, { name: 'bond', type: 'uint256' }, { name: 'appealedAt', type: 'uint256' }, { name: 'status', type: 'uint8' }] }] },
  { type: 'function', name: 'getAppealsByDispute', stateMutability: 'view', inputs: [{ name: 'disputeId', type: 'uint256' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getAppealPeriod', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getAppealBond', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const ReputationStakeABI = [
  { type: 'event', name: 'Staked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'unlockTime', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Unstaked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Slashed', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'reason', type: 'bytes32', indexed: false }] },
  { type: 'error', name: 'InsufficientStake' },
  { type: 'error', name: 'StakeLocked' },
  { type: 'error', name: 'InvalidAmount' },
  { type: 'error', name: 'TransferFailed' },
  { type: 'function', name: 'stake', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }, { name: 'lockDuration', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'unstake', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'slash', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'reason', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'getStakeInfo', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'amount', type: 'uint256' }, { name: 'stakedAt', type: 'uint256' }, { name: 'unlockTime', type: 'uint256' }, { name: 'locked', type: 'bool' }] }] },
  { type: 'function', name: 'totalStaked', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getStakeToken', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
] as const;

export const ReputationOracleABI = [
  { type: 'event', name: 'DataSubmitted', inputs: [{ name: 'dataHash', type: 'bytes32', indexed: true }, { name: 'source', type: 'address', indexed: true }, { name: 'confidence', type: 'uint8', indexed: false }] },
  { type: 'event', name: 'OracleAuthorized', inputs: [{ name: 'oracle', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'OracleRevoked', inputs: [{ name: 'oracle', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'UnauthorizedOracle' },
  { type: 'error', name: 'InvalidData' },
  { type: 'error', name: 'StaleData' },
  { type: 'function', name: 'submitData', stateMutability: 'nonpayable', inputs: [{ name: 'dataHash', type: 'bytes32' }, { name: 'confidence', type: 'uint8' }, { name: 'proof', type: 'bytes' }], outputs: [] },
  { type: 'function', name: 'getData', stateMutability: 'view', inputs: [{ name: 'dataHash', type: 'bytes32' }], outputs: [{ type: 'tuple', components: [{ name: 'dataHash', type: 'bytes32' }, { name: 'timestamp', type: 'uint256' }, { name: 'confidence', type: 'uint8' }, { name: 'source', type: 'address' }] }] },
  { type: 'function', name: 'authorizeOracle', stateMutability: 'nonpayable', inputs: [{ name: 'oracle', type: 'address' }], outputs: [] },
  { type: 'function', name: 'revokeOracle', stateMutability: 'nonpayable', inputs: [{ name: 'oracle', type: 'address' }], outputs: [] },
  { type: 'function', name: 'isAuthorized', stateMutability: 'view', inputs: [{ name: 'oracle', type: 'address' }], outputs: [{ type: 'bool' }] },
] as const;

export const ReputationBoostABI = [
  { type: 'event', name: 'BoostGranted', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'reason', type: 'bytes32', indexed: false }, { name: 'expiresAt', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'BoostRevoked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'boostId', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'BoostExpired', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'boostId', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'BoostNotFound' },
  { type: 'error', name: 'BoostExpiredError' },
  { type: 'error', name: 'UnauthorizedGrant' },
  { type: 'error', name: 'InvalidBoostAmount' },
  { type: 'function', name: 'grantBoost', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'reason', type: 'bytes32' }, { name: 'duration', type: 'uint256' }], outputs: [{ name: 'boostId', type: 'uint256' }] },
  { type: 'function', name: 'revokeBoost', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'boostId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getActiveBoosts', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple[]', components: [{ name: 'amount', type: 'uint256' }, { name: 'expiresAt', type: 'uint256' }, { name: 'reason', type: 'bytes32' }, { name: 'active', type: 'bool' }] }] },
  { type: 'function', name: 'getTotalBoost', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'isBoostActive', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'boostId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
] as const;

export const ReputationDecayABI = [
  { type: 'event', name: 'DecayApplied', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'decayAmount', type: 'uint256', indexed: false }, { name: 'newScore', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'DecayRateUpdated', inputs: [{ name: 'newRate', type: 'uint256', indexed: false }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'DecayIntervalUpdated', inputs: [{ name: 'newInterval', type: 'uint256', indexed: false }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'InvalidDecayRate' },
  { type: 'error', name: 'InvalidInterval' },
  { type: 'function', name: 'applyDecay', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }], outputs: [{ name: 'decayedAmount', type: 'uint256' }] },
  { type: 'function', name: 'calculateDecay', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'setDecayRate', stateMutability: 'nonpayable', inputs: [{ name: 'rate', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setDecayInterval', stateMutability: 'nonpayable', inputs: [{ name: 'interval', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getDecayRate', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getDecayInterval', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getLastDecayTime', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
] as const;

export const ReputationHistoryABI = [
  { type: 'event', name: 'SnapshotRecorded', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'score', type: 'uint256', indexed: false }, { name: 'context', type: 'bytes32', indexed: false }] },
  { type: 'error', name: 'NoHistoryFound' },
  { type: 'function', name: 'recordSnapshot', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'score', type: 'uint256' }, { name: 'context', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'getHistory', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple[]', components: [{ name: 'timestamp', type: 'uint256' }, { name: 'score', type: 'uint256' }, { name: 'context', type: 'bytes32' }] }] },
  { type: 'function', name: 'getHistoryRange', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'start', type: 'uint256' }, { name: 'end', type: 'uint256' }], outputs: [{ type: 'tuple[]', components: [{ name: 'timestamp', type: 'uint256' }, { name: 'score', type: 'uint256' }, { name: 'context', type: 'bytes32' }] }] },
  { type: 'function', name: 'getLatestSnapshot', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'timestamp', type: 'uint256' }, { name: 'score', type: 'uint256' }, { name: 'context', type: 'bytes32' }] }] },
  { type: 'function', name: 'getScoreAtTime', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'timestamp', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantGovernorABI = [
  { type: 'event', name: 'ProposalCreated', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: 'proposer', type: 'address', indexed: true }, { name: 'description', type: 'string', indexed: false }] },
  { type: 'event', name: 'VoteCast', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: 'voter', type: 'address', indexed: true }, { name: 'support', type: 'uint8', indexed: false }, { name: 'votes', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ProposalExecuted', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'ProposalCanceled', inputs: [{ name: 'proposalId', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'InvalidProposal' },
  { type: 'error', name: 'VotingNotStarted' },
  { type: 'error', name: 'VotingEnded' },
  { type: 'error', name: 'VotingNotEnded' },
  { type: 'error', name: 'ProposalNotPassed' },
  { type: 'error', name: 'ProposalAlreadyExecuted' },
  { type: 'error', name: 'UnauthorizedProposer' },
  { type: 'function', name: 'propose', stateMutability: 'nonpayable', inputs: [{ name: 'target', type: 'address' }, { name: 'callData', type: 'bytes' }, { name: 'description', type: 'string' }], outputs: [{ name: 'proposalId', type: 'uint256' }] },
  { type: 'function', name: 'castVote', stateMutability: 'nonpayable', inputs: [{ name: 'proposalId', type: 'uint256' }, { name: 'support', type: 'uint8' }], outputs: [] },
  { type: 'function', name: 'execute', stateMutability: 'nonpayable', inputs: [{ name: 'proposalId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'cancel', stateMutability: 'nonpayable', inputs: [{ name: 'proposalId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getProposal', stateMutability: 'view', inputs: [{ name: 'proposalId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'id', type: 'uint256' }, { name: 'proposer', type: 'address' }, { name: 'description', type: 'string' }, { name: 'callData', type: 'bytes' }, { name: 'target', type: 'address' }, { name: 'forVotes', type: 'uint256' }, { name: 'againstVotes', type: 'uint256' }, { name: 'abstainVotes', type: 'uint256' }, { name: 'startTime', type: 'uint256' }, { name: 'endTime', type: 'uint256' }, { name: 'executed', type: 'bool' }, { name: 'canceled', type: 'bool' }] }] },
  { type: 'function', name: 'getVotes', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'quorum', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'votingDelay', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'votingPeriod', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantTimelockABI = [
  { type: 'event', name: 'OperationScheduled', inputs: [{ name: 'operationId', type: 'bytes32', indexed: true }, { name: 'target', type: 'address', indexed: true }, { name: 'value', type: 'uint256', indexed: false }, { name: 'data', type: 'bytes', indexed: false }, { name: 'scheduledAt', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'OperationExecuted', inputs: [{ name: 'operationId', type: 'bytes32', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'OperationCancelled', inputs: [{ name: 'operationId', type: 'bytes32', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'DelayUpdated', inputs: [{ name: 'newDelay', type: 'uint256', indexed: false }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'OperationAlreadyScheduled' },
  { type: 'error', name: 'OperationNotScheduled' },
  { type: 'error', name: 'OperationNotReady' },
  { type: 'error', name: 'OperationAlreadyExecuted' },
  { type: 'error', name: 'UnauthorizedCaller' },
  { type: 'error', name: 'InvalidDelay' },
  { type: 'function', name: 'schedule', stateMutability: 'nonpayable', inputs: [{ name: 'target', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }, { name: 'delay', type: 'uint256' }], outputs: [{ name: 'operationId', type: 'bytes32' }] },
  { type: 'function', name: 'execute', stateMutability: 'nonpayable', inputs: [{ name: 'target', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }], outputs: [] },
  { type: 'function', name: 'cancel', stateMutability: 'nonpayable', inputs: [{ name: 'operationId', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'setDelay', stateMutability: 'nonpayable', inputs: [{ name: 'newDelay', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getOperation', stateMutability: 'view', inputs: [{ name: 'operationId', type: 'bytes32' }], outputs: [{ type: 'tuple', components: [{ name: 'target', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }, { name: 'scheduledAt', type: 'uint256' }, { name: 'delay', type: 'uint256' }, { name: 'executed', type: 'bool' }] }] },
  { type: 'function', name: 'isOperationReady', stateMutability: 'view', inputs: [{ name: 'operationId', type: 'bytes32' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getMinDelay', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantTokenABI = [
  { type: 'event', name: 'Minted', inputs: [{ name: 'to', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Burned', inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'MaxSupplyExceeded' },
  { type: 'error', name: 'UnauthorizedMinter' },
  { type: 'function', name: 'mint', stateMutability: 'nonpayable', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'burn', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'burnFrom', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setMinter', stateMutability: 'nonpayable', inputs: [{ name: 'minter', type: 'address' }, { name: 'allowed', type: 'bool' }], outputs: [] },
  { type: 'function', name: 'maxSupply', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantTreasuryABI = [
  { type: 'event', name: 'Deposited', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'sender', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Withdrawn', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'recipient', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'BudgetAllocated', inputs: [{ name: 'recipient', type: 'address', indexed: true }, { name: 'token', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'InsufficientBalance' },
  { type: 'error', name: 'UnauthorizedWithdrawal' },
  { type: 'error', name: 'InvalidRecipient' },
  { type: 'function', name: 'deposit', stateMutability: 'payable', inputs: [{ name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }, { name: 'recipient', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'allocateBudget', stateMutability: 'nonpayable', inputs: [{ name: 'recipient', type: 'address' }, { name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getBalance', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getBudget', stateMutability: 'view', inputs: [{ name: 'recipient', type: 'address' }, { name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
] as const;

export const CovenantBridgeABI = [
  { type: 'event', name: 'MessageSent', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'targetChain', type: 'uint16', indexed: true }, { name: 'payload', type: 'bytes', indexed: false }] },
  { type: 'event', name: 'MessageReceived', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'sourceChain', type: 'uint16', indexed: true }, { name: 'payload', type: 'bytes', indexed: false }] },
  { type: 'event', name: 'ChainSupported', inputs: [{ name: 'chainId', type: 'uint16', indexed: true }, { name: 'adapter', type: 'address', indexed: true }] },
  { type: 'error', name: 'InvalidChain' },
  { type: 'error', name: 'InvalidTarget' },
  { type: 'error', name: 'MessageTooLarge' },
  { type: 'error', name: 'UnauthorizedRelayer' },
  { type: 'function', name: 'sendMessage', stateMutability: 'payable', inputs: [{ name: 'targetChain', type: 'uint16' }, { name: 'payload', type: 'bytes' }], outputs: [{ name: 'messageId', type: 'uint256' }] },
  { type: 'function', name: 'receiveMessage', stateMutability: 'nonpayable', inputs: [{ name: 'sourceChain', type: 'uint16' }, { name: 'payload', type: 'bytes' }], outputs: [] },
  { type: 'function', name: 'addSupportedChain', stateMutability: 'nonpayable', inputs: [{ name: 'chainId', type: 'uint16' }, { name: 'adapter', type: 'address' }], outputs: [] },
  { type: 'function', name: 'getMessageStatus', stateMutability: 'view', inputs: [{ name: 'messageId', type: 'uint256' }], outputs: [{ type: 'uint8' }] },
] as const;

export const MessageRelayerABI = [
  { type: 'event', name: 'RelayRequested', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'fee', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'RelayCompleted', inputs: [{ name: 'messageId', type: 'uint256', indexed: true }, { name: 'relayer', type: 'address', indexed: true }] },
  { type: 'error', name: 'RelayNotFound' },
  { type: 'error', name: 'RelayAlreadyCompleted' },
  { type: 'error', name: 'InsufficientFee' },
  { type: 'function', name: 'requestRelay', stateMutability: 'payable', inputs: [{ name: 'targetChain', type: 'uint16' }, { name: 'payload', type: 'bytes' }], outputs: [{ name: 'messageId', type: 'uint256' }] },
  { type: 'function', name: 'completeRelay', stateMutability: 'nonpayable', inputs: [{ name: 'messageId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'claimFee', stateMutability: 'nonpayable', inputs: [{ name: 'messageId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'getRelayJob', stateMutability: 'view', inputs: [{ name: 'messageId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'messageId', type: 'uint256' }, { name: 'targetChain', type: 'uint16' }, { name: 'payload', type: 'bytes' }, { name: 'fee', type: 'uint256' }, { name: 'relayer', type: 'address' }, { name: 'completed', type: 'bool' }] }] },
] as const;

export const MessageVerifierABI = [
  { type: 'event', name: 'MessageVerified', inputs: [{ name: 'messageHash', type: 'bytes32', indexed: true }, { name: 'signer', type: 'address', indexed: true }] },
  { type: 'event', name: 'SignerAuthorized', inputs: [{ name: 'signer', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'SignerRevoked', inputs: [{ name: 'signer', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'InvalidSignature' },
  { type: 'error', name: 'SignerNotAuthorized' },
  { type: 'error', name: 'MessageAlreadyVerified' },
  { type: 'function', name: 'verifyMessage', stateMutability: 'nonpayable', inputs: [{ name: 'messageHash', type: 'bytes32' }, { name: 'signature', type: 'bytes' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'authorizeSigner', stateMutability: 'nonpayable', inputs: [{ name: 'signer', type: 'address' }], outputs: [] },
  { type: 'function', name: 'revokeSigner', stateMutability: 'nonpayable', inputs: [{ name: 'signer', type: 'address' }], outputs: [] },
  { type: 'function', name: 'isAuthorizedSigner', stateMutability: 'view', inputs: [{ name: 'signer', type: 'address' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getVerification', stateMutability: 'view', inputs: [{ name: 'messageHash', type: 'bytes32' }], outputs: [{ type: 'tuple', components: [{ name: 'messageHash', type: 'bytes32' }, { name: 'signature', type: 'bytes' }, { name: 'signer', type: 'address' }, { name: 'verifiedAt', type: 'uint256' }, { name: 'valid', type: 'bool' }] }] },
] as const;

export const CovenantMultiSigABI = [
  { type: 'event', name: 'TransactionSubmitted', inputs: [{ name: 'txIndex', type: 'uint256', indexed: true }, { name: 'submitter', type: 'address', indexed: true }] },
  { type: 'event', name: 'TransactionConfirmed', inputs: [{ name: 'txIndex', type: 'uint256', indexed: true }, { name: 'confirmer', type: 'address', indexed: true }] },
  { type: 'event', name: 'TransactionRevoked', inputs: [{ name: 'txIndex', type: 'uint256', indexed: true }, { name: 'revoker', type: 'address', indexed: true }] },
  { type: 'event', name: 'TransactionExecuted', inputs: [{ name: 'txIndex', type: 'uint256', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'SignerAdded', inputs: [{ name: 'signer', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'SignerRemoved', inputs: [{ name: 'signer', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'event', name: 'RequiredConfirmationsChanged', inputs: [{ name: 'required', type: 'uint256', indexed: false }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'UnauthorizedSigner' },
  { type: 'error', name: 'AlreadyConfirmed' },
  { type: 'error', name: 'NotConfirmed' },
  { type: 'error', name: 'AlreadyExecuted' },
  { type: 'error', name: 'TransactionFailed' },
  { type: 'error', name: 'InvalidSignerCount' },
  { type: 'function', name: 'submitTransaction', stateMutability: 'nonpayable', inputs: [{ name: 'to', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }], outputs: [{ name: 'txIndex', type: 'uint256' }] },
  { type: 'function', name: 'confirmTransaction', stateMutability: 'nonpayable', inputs: [{ name: 'txIndex', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'revokeConfirmation', stateMutability: 'nonpayable', inputs: [{ name: 'txIndex', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'executeTransaction', stateMutability: 'nonpayable', inputs: [{ name: 'txIndex', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'addSigner', stateMutability: 'nonpayable', inputs: [{ name: 'signer', type: 'address' }], outputs: [] },
  { type: 'function', name: 'removeSigner', stateMutability: 'nonpayable', inputs: [{ name: 'signer', type: 'address' }], outputs: [] },
  { type: 'function', name: 'changeRequiredConfirmations', stateMutability: 'nonpayable', inputs: [{ name: 'required', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'isSigner', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getTransaction', stateMutability: 'view', inputs: [{ name: 'txIndex', type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'to', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }, { name: 'executed', type: 'bool' }, { name: 'confirmationCount', type: 'uint256' }] }] },
  { type: 'function', name: 'getTransactionCount', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
] as const;

export const ZKVerifierABI = [
  { type: 'event', name: 'ProofVerified', inputs: [{ name: 'proofHash', type: 'bytes32', indexed: true }, { name: 'valid', type: 'bool', indexed: false }] },
  { type: 'event', name: 'VerifierSet', inputs: [{ name: 'circuitId', type: 'bytes32', indexed: true }, { name: 'verifier', type: 'address', indexed: true }] },
  { type: 'error', name: 'InvalidProof' },
  { type: 'error', name: 'VerifierNotSet' },
  { type: 'error', name: 'VerificationFailed' },
  { type: 'function', name: 'verifyProof', stateMutability: 'nonpayable', inputs: [{ name: 'circuitId', type: 'bytes32' }, { name: 'publicInputs', type: 'uint256[]' }, { name: 'proof', type: 'tuple', components: [{ name: 'a', type: 'uint256[2]' }, { name: 'b', type: 'uint256[2][2]' }, { name: 'c', type: 'uint256[2]' }] }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'setVerifier', stateMutability: 'nonpayable', inputs: [{ name: 'circuitId', type: 'bytes32' }, { name: 'verifier', type: 'address' }], outputs: [] },
  { type: 'function', name: 'getVerifier', stateMutability: 'view', inputs: [{ name: 'circuitId', type: 'bytes32' }], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'hashProof', stateMutability: 'view', inputs: [{ name: 'proof', type: 'tuple', components: [{ name: 'a', type: 'uint256[2]' }, { name: 'b', type: 'uint256[2][2]' }, { name: 'c', type: 'uint256[2]' }] }], outputs: [{ type: 'bytes32' }] },
] as const;

export const COVENTokenABI = [
  { type: 'event', name: 'InflationMinted', inputs: [{ name: 'amount', type: 'uint256', indexed: false }, { name: 'timestamp', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'StakingContractUpdated', inputs: [{ name: 'stakingContract', type: 'address', indexed: true }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'MaxSupplyReached' },
  { type: 'error', name: 'InflationNotDue' },
  { type: 'error', name: 'InvalidInflationRate' },
  { type: 'function', name: 'mintInflation', stateMutability: 'nonpayable', inputs: [], outputs: [{ name: 'amount', type: 'uint256' }] },
  { type: 'function', name: 'burn', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'burnFrom', stateMutability: 'nonpayable', inputs: [{ name: 'account', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setStakingContract', stateMutability: 'nonpayable', inputs: [{ name: 'stakingContract', type: 'address' }], outputs: [] },
  { type: 'function', name: 'getTokenomics', stateMutability: 'view', inputs: [], outputs: [{ type: 'tuple', components: [{ name: 'maxSupply', type: 'uint256' }, { name: 'totalMinted', type: 'uint256' }, { name: 'inflationRate', type: 'uint256' }, { name: 'lastMintTime', type: 'uint256' }] }] },
] as const;

export const RewardDistributorABI = [
  { type: 'event', name: 'RewardsAdded', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'duration', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'RewardsClaimed', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'token', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'error', name: 'NoRewardsAvailable' },
  { type: 'error', name: 'RewardsAlreadyAdded' },
  { type: 'error', name: 'InvalidDuration' },
  { type: 'function', name: 'addRewards', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'duration', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'claimRewards', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [{ name: 'amount', type: 'uint256' }] },
  { type: 'function', name: 'getClaimableRewards', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getDistribution', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'startTime', type: 'uint256' }, { name: 'endTime', type: 'uint256' }, { name: 'claimed', type: 'uint256' }] }] },
] as const;

export const StakingPoolABI = [
  { type: 'event', name: 'Staked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'lockDuration', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Unstaked', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'RewardsClaimed', inputs: [{ name: 'account', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'PoolUpdated', inputs: [{ name: 'accRewardPerShare', type: 'uint256', indexed: false }, { name: '', type: '', indexed: false }] },
  { type: 'error', name: 'InsufficientStake' },
  { type: 'error', name: 'StakeLocked' },
  { type: 'error', name: 'ZeroAmount' },
  { type: 'error', name: 'PoolEmpty' },
  { type: 'function', name: 'stake', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }, { name: 'lockDuration', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'unstake', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'claimRewards', stateMutability: 'nonpayable', inputs: [], outputs: [{ name: 'amount', type: 'uint256' }] },
  { type: 'function', name: 'updatePool', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'getStake', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'tuple', components: [{ name: 'amount', type: 'uint256' }, { name: 'rewardDebt', type: 'uint256' }, { name: 'lockEnd', type: 'uint256' }, { name: 'multiplier', type: 'uint256' }] }] },
  { type: 'function', name: 'pendingRewards', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'totalStaked', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getRewardToken', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'getStakeToken', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
] as const;

export const ERC20ABI = [
  { type: 'function', name: 'name', stateMutability: 'view', inputs: [], outputs: [{ type: 'string' }] },
  { type: 'function', name: 'symbol', stateMutability: 'view', inputs: [], outputs: [{ type: 'string' }] },
  { type: 'function', name: 'decimals', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
  { type: 'function', name: 'totalSupply', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'transfer', stateMutability: 'nonpayable', inputs: [{ name: 'recipient', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'allowance', stateMutability: 'view', inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'approve', stateMutability: 'nonpayable', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'transferFrom', stateMutability: 'nonpayable', inputs: [{ name: 'sender', type: 'address' }, { name: 'recipient', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { type: 'event', name: 'Transfer', inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'Approval', inputs: [{ name: 'owner', type: 'address', indexed: true }, { name: 'spender', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
] as const;
